# Generated by Django 6.0.6 on 2026-06-30 18:38

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='niche_vec',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
        migrations.AlterField(
            model_name='segment',
            name='centroid',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
    ]
