# Generated by Django 6.0.6 on 2026-06-30 20:33

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cases', '0002_alter_case_niche_vec_alter_segment_centroid'),
    ]

    operations = [UnaccentExtension()]
