# Generated by Django 6.0.6 on 2026-09-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_unaccent'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
