# Generated by Django 6.0.6 on 2026-09-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='corte',
            field=models.BooleanField(default=False),
        ),
    ]
